# Generated by Django 5.1.7 on 2025-03-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_yourmodel_alter_admin_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('identity', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='lost_and_found/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
            ],
        ),
    ]
