# Generated by Django 5.1.7 on 2025-03-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
